version: "3.9"
services:
    pg_db:
        image: postgres
        container_name: pg_db
        environment:
#             POSTGRES_USER: 
#             POSTGRES_PASSWORD: 
            POSTGRES_DB: test
            POSTGRES_HOST_AUTH_METHOD: password
        ports:
            - 5432:5432
        volumes:
            - ./pg_data:/var/lib/postgresql/data/
        restart: always
#    pgadmin:
#        image: dpage/pgadmin4
#        container_name: pgadmin
#        environment:
#            PGADMIN_DEFAULT_EMAIL: 
#            PGADMIN_DEFAULT_PASSWORD: 
#            PGADMIN_LISTEN_ADDRESS: 0.0.0.0
#            PGADMIN_LISTEN_PORT: 5050
#        expose:
#            - 5050
#        restart: always
    test:
        build:
            context: ./test
            dockerfile: Dockerfile
        container_name: test
        expose:
            - 5000
        depends_on:
            - pg_db
        restart: always
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
        ports:
            - 443:443
        depends_on:
            - test
#            - pgadmin
        restart: always
    rss_parser:
        build:
            context: ./rss_parser
            dockerfile: Dockerfile
        container_name: rss_parser
        depends_on:
            - pg_db
        restart: always
